#!/bin/bash

set -eu

echo "$ npm install"
npm install --save-dev --legacy-peer-deps "$@"

echo "Check installed packages"
successfully_installed=true
for package_item in "$@"; do
  if echo "$package_item" | grep "@latest"; then
    # Don't perform check for `@latest`, because the installed version number
    # won't match
    continue
  fi

  if ! npm list | grep "$package_item"; then
    successfully_installed=false
    echo "Failed to install: $package_item"
  fi
done

if ! $successfully_installed; then
  echo "Installed packages:"
  npm list
  exit 1
fi
